### ISSUE TITLE
Explore non-Node testing options

### ISSUE THREAD

**Issue by delaneyj** [starfederation/datastar-restructure-interim#30]
I wasn't aware playwright-go still uses Node... looking into alternatives to keep pure Go

**Comment by qualk** [comment]
[Rod](https://github.com/go-rod/rod) [possibly](https://go-rod.github.io/#/why-rod?id=playwright)?

**Comment by zangster300** [comment]
https://github.com/starfederation/datastar/tree/develop/code/go/site/smoketests
